//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AffdexMe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Joy</string>
  <string>Sadness</string>
  <string>Anger</string>
  <string>Disgust</string>
  <string>Surprise</string>
  <string>Fear</string>
  <string>Attention</string>
  <string>Engagement</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Classifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Classifiers"]));
            }
            set {
                this["Classifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPoints {
            get {
                return ((bool)(this["ShowPoints"]));
            }
            set {
                this["ShowPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMeasurements {
            get {
                return ((bool)(this["ShowMeasurements"]));
            }
            set {
                this["ShowMeasurements"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Affectiva\\sdk_peter.walker@kantar.com.license")]
        public string LicencePath {
            get {
                return ((string)(this["LicencePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Affectiva\\Affdex SDK\\data")]
        public string DataPath {
            get {
                return ((string)(this["DataPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mwcfacialmoodencoding")]
        public string AzureEventHubName {
            get {
                return ((string)(this["AzureEventHubName"]));
            }
            set {
                this["AzureEventHubName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Endpoint=sb://mwcfacialmoodencoding-ns.servicebus.windows.net/;SharedAccessKeyNam" +
            "e=SendRule;SharedAccessKey=MGcJt1sZt/OErdQdQeVaW6syvvjEnoMf2oW4Ky3vuDs=")]
        public string AzureEventHubEndPoint {
            get {
                return ((string)(this["AzureEventHubEndPoint"]));
            }
            set {
                this["AzureEventHubEndPoint"] = value;
            }
        }
    }
}
